# Each new term in the Fibonacci sequence is generated by adding the 
# previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 		1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not 
# exceed four million, find the sum of the even-valued terms.


def fib(a, b, num)
	arr = []
	fib_num = 0
	while fib_num < num
		fib_num = a + b
		arr << fib_num if fib_num < num
		a = b
		b = fib_num
	end
	add_only_even(arr)
end

def add_only_even(fib_nums)
	sum = 0
	fib_nums.each do |x|
		sum += x if x.even?
	end
	sum
end

p fib(0, 1, 100) == 44
p fib(0, 1, 4_000_000) == 4613732